CREATE DATABASE AMAZON;

USE AMAZON;

-- PRODUCTS TABLE
CREATE TABLE PRODUCT (
  P_ID int AUTO_INCREMENT,
  P_NAME varchar(225) NOT NULL UNIQUE,
  P_QUANTITY int NOT NULL,
  P_PRICE int NOT NULL,
  AVL_COUNT int NOT NULL CHECK (AVL_COUNT >= 0),
  EXPAIR_DATE date DEFAULT NULL,
  PRIMARY KEY (P_ID)
); 
INSERT INTO PRODUCT 
VALUES(17264, 'REALME 6i', 1, 13000, 40, NULL);

-- DEPARTMENTS TABLE
CREATE TABLE DEPARTMENT (
  DEP_ID int NOT NULL,
  DEP_NAME varchar(225) NOT NULL,
  PRIMARY KEY (DEP_ID),
  UNIQUE KEY (DEP_NAME)
);

-- EMPLOYEES TABLE
CREATE TABLE EMPLOYEE (
  EMP_ID int NOT NULL AUTO_INCREMENT,
  EMP_NAME varchar(225) NOT NULL,
  EMP_DOB date NOT NULL,
  EMP_AGE int NOT NULL CHECK(EMP_AGE >= 21),
  EMP_SALARY decimal(10,2) NOT NULL CHECK ((EMP_SALARY >= 0) and (EMP_SALARY <= 100000)),
  EMP_JOINDATE date NOT NULL,
  EMP_PHOTO blob,
  DEP_ID int DEFAULT NULL,
  PRIMARY KEY (EMP_ID),
  KEY DEP_ID (DEP_ID),
  FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_DOB, EMP_AGE, EMP_SALARY, EMP_JOINDATE, EMP_PHOTO, DEP_ID)
VALUES('675421', 'Eswar', '2003-06-02', '21', 87000, '2025-01-12',NULL, 72345);

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMER (
  C_ID int PRIMARY KEY AUTO_INCREMENT,
  C_NAME varchar(225) NOT NULL,
  C_CONTACT bigint NOT NULL UNIQUE,
  C_ADDRESS text NOT NULL
);
INSERT INTO CUSTOMER(C_ID, C_NAME, C_CONTACT, C_ADDRESS)
VALUES
(265332, 'ESWAR', 6302758340, 'PUDIPATLA, TIRUPATHI, 517505'),
(265333, 'ARJUN', 9927382684, 'PUDIPATLA, TIRUPATHI, 517505'),
(265334, 'KRISHNA', 9927639273, 'MALAVARAM, TIRUPATHI, 517505'),
(265336, 'ABHI', 9973258326, 'MALAVARAM, TIRUPATHI, 517505');

-- ORDERS TABLE
CREATE TABLE ORDERS (
    O_ID INT PRIMARY KEY AUTO_INCREMENT,
    O_DATETIME DATETIME DEFAULT NOW(),
    P_ID INT,
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);
INSERT INTO ORDERS(O_ID,P_ID, C_ID) 
VALUES(178253,17263,265332);