-- > CREATING TABLES FOR VIWE CONCEPTS PRACTICE.

-- CREATING VIEW DATABASE
CREATE DATABASE VIEWS_DB;

-- > STORE HAVE PRODUCTS. 
-- > PRODUCT HAVE ID, NAME, PRICE, AVL_COUNT, EXPAIR_DATE .
CREATE TABLE VIEWS_DB.PRODUCTS(
	P_ID INT PRIMARY KEY AUTO_INCREMENT,
	P_NAME VARCHAR(225) NOT NULL UNIQUE,
	P_QUANTITY INT NOT NULL,
	P_PRICE INT NOT NULL,
	AVL_COUNT INT NOT NULL CHECK(AVL_COUNT >= 0),
	EXPAIR_DATE DATE -- DATE NOT SUPPORT DEFAULT VALUES
);


CREATE TABLE VIEWS_DB.DEPARTMENT(
	DEP_ID INT PRIMARY KEY,
	DEP_NAME VARCHAR(225) NOT NULL UNIQUE
);

-- > EMPLOYEE HAVE ID, NAME, AGE, SALARY, JOINDATE, PHOTO .
CREATE TABLE VIEWS_DB.EMPLOYEE (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(225) NOT NULL,
    EMP_DOB DATE NOT NULL,
    EMP_AGE INT NOT NULL CHECK (EMP_AGE >= 21),
    EMP_SALARY DECIMAL(10,2) NOT NULL CHECK (EMP_SALARY >= 0 AND EMP_SALARY <= 100000),
    EMP_JOINDATE DATE NOT NULL,
    EMP_PHOTO BLOB NULL,
    DEP_ID INT,
    FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);


-- > CUSTOMERS HAVE C_ID, C_NAME, C_CONTACT, C_ADDRESS
CREATE TABLE CUSTOMER(
	C_ID INT PRIMARY KEY AUTO_INCREMENT,
	C_NAME VARCHAR(225) NOT NULL,
	C_CONTACT BIGINT NOT NULL UNIQUE,
	C_ADDRESS TEXT NOT NULL
);

-- > ORDER HAVE O_ID, P_ID, C_ID, O_DATE, O_TIME
CREATE TABLE ORDERS (
    O_ID INT PRIMARY KEY AUTO_INCREMENT,
    O_DATE DATE DEFAULT NOW(),
    O_TIME TIME DEFAULT NOW(),
    P_ID INT,
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);

-- 
-- > VIEW FOR EMPLOYEE WORKING IN WHICH DEPARTMENT.
CREATE VIEW EMP_DEP_DATA AS
SELECT 
		E.EMP_ID, 
		E.EMP_NAME, 
        D.DEP_NAME
FROM 
	EMPLOYEE E 
JOIN 
	DEPARTMENT D 
ON 
	E.DEP_ID = D.DEP_ID;