SELECT * FROM views_db.customer_order_details;

SELECT * FROM views_db.customer_order_details LIMIT 1;

CREATE VIEW CUSTOMER_ORDER_DETAILS AS 
SELECT 
    C.C_ID AS CUSTOMER_ID,
    C.C_NAME AS CUSTOMER_NAME, 
    C.C_CONTACT AS CUSTOMER_CONTACT_NO,
    O.O_ID AS ORDER_ID,
    P.P_NAME AS PRODUCT_NAME,
    P.P_PRICE AS PRODUCT_PRICE
FROM 
    CUSTOMER C 
JOIN 
    ORDERS O ON C.C_ID = O.C_ID
JOIN
    PRODUCT P ON O.P_ID = P.P_ID
WHERE 
    P.P_PRICE > 5000;
