-- DCL DATA CONTROL LANGUAGE: GRANT, REVOKE:

-- CREATING ROOT USER
CREATE USER 'USER_NAME' IDENTIFIED BY 'PASSWORD';

GRANT ALL PRIVILEGES ON COLLEGE.* TO 'USER_NAME';

REVOKE ALL PRIVILEGES ON COLLEGE.* FROM 'USER_NAME';

DROP USER USER_NAME;


