-- SQL COMMENDS:
-- DDL - CREATE, ALTER, DROP
-- CREATE IS USED TO CREATE DB OBJECTS.
-- ALTER IS USED TO MODIFY THE EXISTING STRUCTURE

CREATE TABLE SAM(
ID INT);

DESC SAM;

-- ADDING NEW COLUMN INTO EXTSTING TABLE:
ALTER TABLE SAM ADD COLUMN EMAIL VARCHAR(50);

-- DELETING COLUMN FROM EXISTING TABLE:
ALTER TABLE SAM DROP COLUMN ID;

-- RENAMING EMAIL COLUMN TO 'STUDENT_EMAIL' & CHANGING DATA TYPE:
ALTER TABLE SAM CHANGE EMAIL STUDENT_EMAIL VARCHAR(70);

-- CHANGING ONLY DATA TYPE:
ALTER TABLE SAM MODIFY COLUMN STUDENT_EMAIL CHAR(20); -- MODIFY KEYWORD IS USED TO CHANGE ONLY DATA TYPE

-- RENAMING THE TABLE NAME:
ALTER TABLE SAM RENAME TO SAMPLE;
