
-- DML COMMENDS:

CREATE TABLE DML_OPERATIONS(
OP_ID INT,
OP_TYPE VARCHAR(30));

INSERT INTO DML_OPERATIONS VALUES
(101,'TYPE1'),(102,'TYPE2'),(103,'TYPE3'),(104,'TYPE4');

SELECT * FROM DML_OPERATIONS;

-- WAQ TO UPDATE TYPE3 TO TYPE-THREE.
UPDATE DML_OPERATIONS
SET OP_TYPE = 'TYPE-THREE'
WHERE OP_TYPE = 'TYPE3'; -- UPDATE TEMP ONLY

-- WAQ TO UPDATE THE OP_ID TO 1002 FOR TYPE2 OPERATION.
UPDATE DML_OPERATIONS
SET OP_ID = 1002
WHERE OP_TYPE = 'TYPE2';

-- CHANGING MYSQL UPDATE ADMIN ACCESS
SET SQL_SAFE_UPDATES = 0;

-- WAQ TO UPDATE THE FIRST_NAME OF 'HEMA' TO 'JAYA' FOR EMP TABLE.

-- DELETE: WAQ TO DELETE THE RECORD WHERE OP_ID IS 103. 
DELETE FROM DML_OPERATIONS
WHERE OP_ID = 103; -- WITH OUT WHERE CONDITION WE SHOULD NOT EXECUTE DELETE COMMEND!

-- DROP TABLE 

-- TRUNCATE: DELETING ALL RECORDS BUT NOT TABLE STRUCTURE
TRUNCATE TABLE DML_OPERATIONS;

-- DIFFERENCE BETWEEN DELETE, DROP AND TRUNCATE?
