-- INNER JOIN QUERY--

CREATE DATABASE UNIVERSITY;

CREATE TABLE DEPARTMENT(
			DEP_ID INT PRIMARY KEY, 
			DEP_NAME VARCHAR(225) NOT NULL UNIQUE
);

CREATE TABLE STUDENT(
			STU_ROLLNO INT PRIMARY KEY,
            STU_NAME VARCHAR(225) NOT NULL,
            STU_DOB DATE NOT NULL,
            STU_CONTACT BIGINT NOT NULL UNIQUE,
            STU_ADDRESS TEXT NOT NULL,
            DEP_ID INT,
            FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);

CREATE TABLE STU_RESULT(
			JAVA INT NOT NULL DEFAULT 0,
            DBMS INT NOT NULL DEFAULT 0,
            BIGDATA INT NOT NULL DEFAULT 0,
            MYSQL INT NOT NULL DEFAULT 0,
            STU_ROLLNO INT,
            FOREIGN KEY (STU_ROLLNO) REFERENCES STUDENT(STU_ROLLNO)
);
            
-- INNER JOIN QUERY USING ABOVE THREE TABLES
SELECT 
	S.STU_ROLLNO AS ROLLNO, S.STU_NAME AS NAME, S.STU_DOB AS DATE_OF_BIRTH, S.STU_CONTACT AS CONTACT,
	R.JAVA, R.DBMS, R.MYSQL, R.BIGDATA,
    D.DEP_NAME AS BRANCH
FROM STUDENT S 
JOIN STU_RESULT R ON S.STU_ROLLNO = R.STU_ROLLNO	-- WHERE STUDENT TABLE ROWS == RESULT TABLE ROW DATA GET
JOIN DEPARTMENT D ON S.DEP_ID = D.DEP_ID	-- WHERE STUDENT TABLE ROWS == DEPARTMENT TABLE ROW 
WHERE S.STU_ROLLNO = 250;	-- WHERE S.ROLLNO = ?