CREATE DATABASE JOINS;

CREATE TABLE CUSTOMER(
C_ID INT PRIMARY KEY,	-- Make P_ID the primary key
C_NAME VARCHAR(25),
C_CONTACT INT,
C_ADDRESS VARCHAR(50),
P_ID INT
);


CREATE TABLE PRODUCT(
    P_ID INT PRIMARY KEY,  -- Make P_ID the primary key
    P_NAME VARCHAR(25),
    P_TITLE VARCHAR(50),
    P_DESCRIPTION VARCHAR(225)
);


CREATE TABLE PURCHASE(
    PURCHASE_ID INT PRIMARY KEY,
    C_ID INT,
    P_ID INT,
    PURCHASE_DATE DATE,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);

