CREATE TABLE DEPARTMENTS(
DEP_ID INT PRIMARY KEY,
DEP_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(50) NOT NULL,
EMP_DOB DATE NOT NULL,
EMP_CONTACT_NO INT NOT NULL UNIQUE,
EMP_DEPARTMENT_ID INT NOT NULL,
EMP_SALARY INT NOT NULL,
FOREIGN KEY (EMP_DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEP_ID));