-- TCL TRANSACTION CONTROL LANGUAGE: COMMIT, ROLLBACK, SAVEPOINT:

CREATE TABLE BANK(
BANK_ID INT);

-- CHANGING MYSQL COMMIT ADMIN ACCESS
SET AUTOCOMMIT = 0;

INSERT INTO BANK VALUES(11),(22);
COMMIT;
INSERT INTO BANK VALUE(33),(44);
ROLLBACK; -- ROLLBACK IS USED TO (UNDO) THE LAST COMMIT STATEMENTS

-- COMMIT, SAVEPOINT
INSERT INTO BANK VALUES(11),(22);
COMMIT;
INSERT INTO BANK VALUE(33),(44);
SAVEPOINT S1;
INSERT INTO BANK VALUES(55),(66);
SAVEPOINT S2;
INSERT INTO BANK VALUES(77),(88);
ROLLBACK TO S1;
ROLLBACK TO S2;
